# See comment in src/main.rs for the purpose of this crate
[package]
name = "matrixcompare-minimal"
version = "0.1.0"
edition = "2018"

[dependencies]
matrixcompare = { version = "0.1.4", path = ".." }
