name: Build and run tests

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ubuntu:

    name: Test on Ubuntu
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Update Rust
      run: rustup update

    - name: Run tests
      run: cargo test --all-targets

  windows:

    name: Test on Windows
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          cargo test --all-targets
        shell: cmd

